language: ruby
rvm:
  - "2.1.5"
addons:
  postgresql: "9.3"
  code_climate:
    repo_token:
      secure: "Xcq5V0dBe/aVuXwf41o7F1knTWxbJXong6HRyLVBQ5Y0TqoHiRXS+83lKv6Jm4sF6ejvfuiuQe33qYjpbkgvJMhn1hvl5GC8h6Y1VfR5OBepHVjRdd3FsYIltXfMR5CQzIajcCwFLcZtRicIHhOMkXec2EqDVqJT9SNIDVGEezs="
before_script:
  - psql -c 'create database workshop_test;' -U postgres
notifications:
  hipchat:
    rooms:
      secure: "i58U0Wh1sX3AlD3VfFEMMcMoMwu0LBmrFDvnZw6DCd1GARto/GuK38myqFYXdyz3Z92m8lxte13X5lrMKYroijWE1iIubXnt5vh+TCp1EkkS+EF5tgWXODC+6gNgHNKavWqclIR749YYJkYxNJo7qkfO3Lt49APjulmnvdn5i60=" 
