language: ruby
rvm:
  - "2.1.3"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database workshop_test;' -U postgres
notifications:
  hipchat:
    rooms:
      secure: IUpBexAPQzt9HK1joD9nHxsqw26KvFVYZyuWw8UswztKDyuJJMVJhyd/r4m/BihX4/0iUidlyU8efLPh8Se5oN5wcBSrEINgj3AgNShJpuarVtqYIgIzUIF8GJwFa0NcuFvpuky/OeAxdIU5UMxxdsX3LcCuuV+sQeDZJHCOJ0A=
